In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [3]:
# Sourcing and Opening File

path = "F:/Users/MSR/Downloads/Amazon E-commerce/products.csv"

df_prod = pd.read_csv(path)
# df_rvew = pd.read_csv(path + "reviews.csv")

print(df_prod.head)
print("\n" + "_"*50 + "\n")
print(df_prod.describe())
print("\n" + "_"*50 + "\n")
print(df_prod.info())
print("\n" + "_"*50 + "\n")
print(df_prod.shape)

<bound method NDFrame.head of      s.no                                         about_item        asin  \
0       0  Premium Comfort: Crafted from a high-quality c...  B0B59BJG6Y
1       1  Material: Men's polo shirt is made of soft pol...  B0DLGB4RYH
2       2  PERFORMANCE:These men polo shirts are soft,lig...  B0DRXF62JH
3       3  【Material】: These golf shirts for men are made...  B0DK5FZ325
4       4  MOISTURE WICKING: The fabric of the summer gol...  B0BGXTC1FR
..    ...                                                ...         ...
723  1007  Comfortable High-Waist Fit: These cargo jean w...  B0D9G8FPF1
724  1008  Buttery-Soft & Comfortable: Trendy jean look b...  B0BN1PZ1VX
725  1009  Jean For Women Excellent Workmanship, No Odor,...  B0C1L9X2Y7
726  1010  Materials: Lepunuo Cargo Pants are made of hig...  B0C38W6M1C
727  1011  Material:The cargo jeans are made 70%Cotton,23...  B0C2VD1HN2

    availability                                  best_sellers_rank  \
0       In Stock  #56,836 in Clothing, Shoes & Jewelry (See Top ...
1       In Stock  #50,261 in Clothing, Shoes & Jewelry (See Top ...
2       In Stock  #69,641 in Clothing, Shoes & Jewelry (See Top ...
3       In Stock  #194,649 in Clothing, Shoes & Jewelry (See Top...
4       In Stock  #3,664 in Clothing, Shoes & Jewelry (See Top 1...
..           ...                                                ...
723     In Stock                                                NaN
724     In Stock                                                NaN
725     In Stock                                                NaN
726     In Stock                                                NaN
727     In Stock                                                NaN

          brand_name                                     brand_page_url  \
0       MLYENX Store  https://www.amazon.com/stores/MLYENX/page/1FCD...
1     COOFANDY Store  https://www.amazon.com/stores/COOFANDY/page/23...
2         ZITY Store  https://www.amazon.com/stores/ZITY/page/F582B6...
3        Rouen Store  https://www.amazon.com/stores/ROUEN/page/4C407...
4    V VALANCH Store  https://www.amazon.com/stores/VVALANCH/page/0E...
..               ...                                                ...
723    Brand: QICAMO                                                NaN
724   VOOVEEYA Store  https://www.amazon.com/stores/VOOVEEYA/page/54...
725     ETTELO Store  https://www.amazon.com/stores/ETTELODenimFashi...
726    Lepunuo Store  https://www.amazon.com/stores/Lepunuo/page/C6F...
727    GuYongZ Store  https://www.amazon.com/stores/GuYongZ/page/9D3...

                                           breadcrumbs  \
0    Clothing, Shoes & Jewelry › Men › Clothing › A...
1    Clothing, Shoes & Jewelry › Men › Clothing › S...
2    Clothing, Shoes & Jewelry › Men › Clothing › A...
3    Clothing, Shoes & Jewelry › Men › Clothing › A...
4    Clothing, Shoes & Jewelry › Men › Clothing › A...
..                                                 ...
723  Clothing, Shoes & Jewelry › Women › Clothing ›...
724  Clothing, Shoes & Jewelry › Sport Specific Clo...
725  Clothing, Shoes & Jewelry › Women › Clothing ›...
726  Clothing, Shoes & Jewelry › Women › Clothing ›...
727  Clothing, Shoes & Jewelry › Women › Clothing ›...

                               customer_review_summary default_variant/0  ...  \
0    Customers find the shirts comfortable and well...        size:Large  ...
1                                                  NaN      size:X-Large  ...
2                                                  NaN      size:X-Large  ...
3                                                  NaN        size:Small  ...
4    Customers find the shirt has a good fit and lo...      size:X-Large  ...
..                                                 ...               ...  ...
723  Customers find the pants comfortable and well-...            size:6  ...
724  Customers find the pants comfortable and well-...        size:Large  ...
725  Customers appreciate the pants' flattering des...            size:8  ...
726  Customers find the pants comfortable and flatt...       size:Medium  ...
727  Customers appreciate the pants' color and mate...        size:Large  ...

    rating_distribution/4star rating_distribution/5star        rating_stars  \
0                         15%                       75%  4.6 out of 5 stars
1                         17%                       66%  4.4 out of 5 stars
2                         37%                       63%  4.6 out of 5 stars
3                         20%                       80%  4.8 out of 5 stars
4                         17%                       69%  4.4 out of 5 stars
..                        ...                       ...                 ...
723                       18%                       67%  4.4 out of 5 stars
724                       13%                       70%  4.4 out of 5 stars
725                       16%                       53%  3.9 out of 5 stars
726                       17%                       60%  4.2 out of 5 stars
727                       10%                       50%  3.7 out of 5 stars

    recent_purchases       scrape_time   seller_name  \
0         50+ bought  03-10-2025 21:42     Greenfive
1                NaN  03-10-2025 21:42      COOFANDY
2                NaN  03-10-2025 21:42         ZITY®
3                NaN  03-10-2025 21:43  MICHEL ROUEN
4                NaN  03-10-2025 21:43   Zhengdaqian
..               ...               ...           ...
723      300+ bought  03-11-2025 02:15    GlobeCarry
724      600+ bought  03-11-2025 02:15      VooVeeYA
725      100+ bought  03-11-2025 02:15        ETTELO
726       2K+ bought  03-11-2025 02:15       Lepunuo
727       50+ bought  03-11-2025 02:15         crazm

                                       seller_page_url  \
0    https://www.amazon.com/gp/help/seller/at-a-gla...
1    https://www.amazon.com/gp/help/seller/at-a-gla...
2    https://www.amazon.com/gp/help/seller/at-a-gla...
3    https://www.amazon.com/gp/help/seller/at-a-gla...
4    https://www.amazon.com/gp/help/seller/at-a-gla...
..                                                 ...
723  https://www.amazon.com/gp/help/seller/at-a-gla...
724  https://www.amazon.com/gp/help/seller/at-a-gla...
725  https://www.amazon.com/gp/help/seller/at-a-gla...
726  https://www.amazon.com/gp/help/seller/at-a-gla...
727  https://www.amazon.com/gp/help/seller/at-a-gla...

                                                 title  \
0    4/5 Pack Mens Polo Shirts Short Sleeve Quick D...
1    COOFANDY Men's Polo Shirts Short Sleeve Moistu...
2    ZITY 3 Pack Men Polo Shirts Short Sleeve with ...
3    Rouen Mens Golf Shirt Moisture Wicking Dry Fit...
4    V VALANCH Mens Polo Shirts Short Sleeve Moistu...
..                                                 ...
723  Women High Waisted Cargo Jean for Women with 6...
724  VOOVEEYA Women's Bootcut Leggings - Bootleg Yo...
725  Womens Jeans Mid Waisted Straight Leg Loose St...
726  Lepunuo Cargo Pants for Women High Waisted Cas...
727                          Women's Cargo Jeans Pants

                                            all_images rank_1
0    ['https://m.media-amazon.com/images/I/41yUF65P...   85.0
1    ['https://m.media-amazon.com/images/I/31a3mSs3...  199.0
2    ['https://m.media-amazon.com/images/I/41J5q-Ua...  111.0
3    ['https://m.media-amazon.com/images/I/31J1ttvf...  266.0
4    ['https://m.media-amazon.com/images/I/31Ff+3Ib...   11.0
..                                                 ...    ...
723  ['https://m.media-amazon.com/images/I/41l66GgY...    NaN
724  ['https://m.media-amazon.com/images/I/318Pke7A...    NaN
725  ['https://m.media-amazon.com/images/I/31Y0KzBg...    NaN
726  ['https://m.media-amazon.com/images/I/31qOVkbm...    NaN
727  ['https://m.media-amazon.com/images/I/41ZWjcrz...    NaN

[728 rows x 34 columns]>

__________________________________________________

              s.no  price_value      rank_1
count   728.000000   707.000000  540.000000
mean    423.361264    35.323948  174.622222
std     293.923401    26.422336  240.115097
min       0.000000     5.457300    1.000000
25%     184.750000    19.990000   18.000000
50%     371.500000    28.950000   56.500000
75%     553.250000    41.771600  220.250000
max    1011.000000   249.990000  994.000000

__________________________________________________

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 728 entries, 0 to 727
Data columns (total 34 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   s.no                       728 non-null    int64
 1   about_item                 728 non-null    object
 2   asin                       728 non-null    object
 3   availability               715 non-null    object
 4   best_sellers_rank          558 non-null    object
 5   brand_name                 728 non-null    object
 6   brand_page_url             649 non-null    object
 7   breadcrumbs                715 non-null    object
 8   customer_review_summary    634 non-null    object
 9   default_variant/0          696 non-null    object
 10  default_variant/1          658 non-null    object
 11  default_variant/2          1 non-null      object
 12  delivery_date              702 non-null    object
 13  fastest_delivery_date      667 non-null    object
 14  list_price                 401 non-null    object
 15  manufacturer               266 non-null    object
 16  model_number               199 non-null    object
 17  price_value                707 non-null    float64
 18  product_description        271 non-null    object
 19  product_url                728 non-null    object
 20  rating_count               719 non-null    object
 21  rating_distribution/1star  728 non-null    object
 22  rating_distribution/2star  728 non-null    object
 23  rating_distribution/3star  728 non-null    object
 24  rating_distribution/4star  728 non-null    object
 25  rating_distribution/5star  728 non-null    object
 26  rating_stars               719 non-null    object
 27  recent_purchases           569 non-null    object
 28  scrape_time                728 non-null    object
 29  seller_name                707 non-null    object
 30  seller_page_url            426 non-null    object
 31  title                      728 non-null    object
 32  all_images                 728 non-null    object
 33  rank_1                     540 non-null    float64
dtypes: float64(2), int64(1), object(31)
memory usage: 193.5+ KB
None

__________________________________________________

(728, 34)

In [28]:

df_prod1 = df_prod.copy()

# Print the first 5 unique raw values to inspect the exact characters
print(df_prod1['breadcrumbs'].dropna().unique()[:5])
# 2. Filter down to the specific target domain: Men's Clothing
# df_men = df[df['category_path'] == 'Clothing, Shoes & Jewelry > Men > Clothing'].copy()

# 3. Calculate the number of clicks by counting the '>' occurrences (actions - 1)
# If there are no '>', it means 1 standalone action occurred. 
# df_prod1['number_of_clicks'] = df_prod1['breadcrumbs'].apply(lambda x: x.count('>') + 1 if '>' in x else 1)
# Fixed code line:

# Use the exact character from your data: '›'
TARGET_SEPARATOR = '›'

# Calculate the hierarchy depth (clicks needed to navigate) safely
df_prod1['number_of_clicks'] = df_prod1['breadcrumbs'].astype(str).apply(
    lambda x: x.count(TARGET_SEPARATOR) + 1 if TARGET_SEPARATOR in x else 1
)

# Display the processed dataframe
print("--- Filtered Men's Clothing Click Dataset ---")
df_prod1[['breadcrumbs', 'number_of_clicks','availability','rating_stars', 'recent_purchases']]

['Clothing, Shoes & Jewelry › Men › Clothing › Active › Active Shirts & Tees › Polos'
 'Clothing, Shoes & Jewelry › Men › Clothing › Shirts › Polos'
 'Clothing, Shoes & Jewelry › Men › Clothing › Underwear › Undershirts'
 'Clothing, Shoes & Jewelry › Men › Clothing › Shirts › T-Shirts'
 'Clothing, Shoes & Jewelry › Boys › Clothing › Underwear › Undershirts']
--- Filtered Men's Clothing Click Dataset ---

,breadcrumbs,number_of_clicks,availability,rating_stars,recent_purchases
0,"Clothing, Shoes & Jewelry › Men › Clothing › A...",6,In Stock,4.6 out of 5 stars,50+ bought
1,"Clothing, Shoes & Jewelry › Men › Clothing › S...",5,In Stock,4.4 out of 5 stars,NaN
2,"Clothing, Shoes & Jewelry › Men › Clothing › A...",6,In Stock,4.6 out of 5 stars,NaN
3,"Clothing, Shoes & Jewelry › Men › Clothing › A...",6,In Stock,4.8 out of 5 stars,NaN
4,"Clothing, Shoes & Jewelry › Men › Clothing › A...",6,In Stock,4.4 out of 5 stars,NaN
...,...,...,...,...,...
723,"Clothing, Shoes & Jewelry › Women › Clothing ›...",4,In Stock,4.4 out of 5 stars,300+ bought
724,"Clothing, Shoes & Jewelry › Sport Specific Clo...",5,In Stock,4.4 out of 5 stars,600+ bought
725,"Clothing, Shoes & Jewelry › Women › Clothing ›...",4,In Stock,3.9 out of 5 stars,100+ bought
726,"Clothing, Shoes & Jewelry › Women › Clothing ›...",5,In Stock,4.2 out of 5 stars,2K+ bought
727,"Clothing, Shoes & Jewelry › Women › Clothing ›...",4,In Stock,3.7 out of 5 stars,50+ bought

In [4]:

 path_ = "F:/Users/MSR/Downloads/Amazon E-commerce/reviews.csv"
df_rvew = pd.read_csv(path_)

print(df_rvew.head)
print("\n" + "_"*50 + "\n")
print(df_rvew.describe())
print("\n" + "_"*50 + "\n")
print(df_rvew.info())
print("\n" + "_"*50 + "\n")
print(df_rvew.shape)

<bound method NDFrame.head of        s.no  helpfulVoteCount images/0 images/1 images/2 images/3 images/4  \
0         0                 0      NaN      NaN      NaN      NaN      NaN
1         1                 0      NaN      NaN      NaN      NaN      NaN
2         2                 0      NaN      NaN      NaN      NaN      NaN
3         3                 0      NaN      NaN      NaN      NaN      NaN
4         4                 0      NaN      NaN      NaN      NaN      NaN
...     ...               ...      ...      ...      ...      ...      ...
6322  14046                 0      NaN      NaN      NaN      NaN      NaN
6323  14047                 2      NaN      NaN      NaN      NaN      NaN
6324  14048                 0      NaN      NaN      NaN      NaN      NaN
6325  14049                 0      NaN      NaN      NaN      NaN      NaN
6326  14050                 0      NaN      NaN      NaN      NaN      NaN

     images/5 images/6 images/7  ...        reviewID  \
0         NaN      NaN      NaN  ...  R2AUQFPJY5ERCZ
1         NaN      NaN      NaN  ...  R1YNLJ0QFLB1VT
2         NaN      NaN      NaN  ...  R11LIYW9RMDK9R
3         NaN      NaN      NaN  ...  R3K9X391DJNTPZ
4         NaN      NaN      NaN  ...   RP17IW9ZKENDZ
...       ...      ...      ...  ...             ...
6322      NaN      NaN      NaN  ...   RABGOTWKLC1ZE
6323      NaN      NaN      NaN  ...  R296C450ZKYYFX
6324      NaN      NaN      NaN  ...  R3GH9SCGO3DZPU
6325      NaN      NaN      NaN  ...  R3RUVOQYCGQB74
6326      NaN      NaN      NaN  ...   R84TV4CYOWGTW

                                         reviewMetadata  reviewPosition  \
0        Reviewed in the United States on March 6, 2025               1
1        Reviewed in the United States on March 7, 2025               1
2     Reviewed in the United States on February 27, ...               2
3     Reviewed in the United States on February 26, ...               3
4     Reviewed in the United States on February 20, ...               4
...                                                 ...             ...
6322  Reviewed in the United States on February 13, ...               6
6323  Reviewed in the United States on October 25, 2024               7
6324  Reviewed in the United States on November 28, ...               8
6325  Reviewed in the United States on February 27, ...               9
6326  Reviewed in the United States on December 16, ...              10

                                             reviewText  \
0     ‚úçÔ∏è The COOFANDY Men's Polo Shirt is a fant...
1     I love these. They look good. They fit well. T...
2     My expectations were low -- how good could shi...
3     This 3-pack of multi-color shirts is really a ...
4     With these three polo shirts I was very satisf...
...                                                 ...
6322  Super cute! They just shrunk after I washed th...
6323  I've been looking for a good 'boyfriend fit' p...
6324  They look so good on and give you a booty lift...
6325  The Pants ran big on me. It could be that I do...
6326  Ordered for my daughter, they were a little lo...

                                            reviewTitle  \
0           Stylish and Lightweight COOFANDY Polo Shirt
1                                   New favorite shirts
2                                  Incredibly Good Deal
3     Higher quality & breathable 3-pack shirt set t...
4                               Pocket Polos Looks Good
...                                                 ...
6322                                          Shrinkage
6323                                     Great purchase
6324                                      Look amazing!
6325                                           Runs big
6326                                               CUTE

                                         reviewURL verifiedPurchase videos/0  \
0     https://www.amazon.com/review/R2AUQFPJY5ERCZ            False      NaN
1     https://www.amazon.com/review/R1YNLJ0QFLB1VT            False      NaN
2     https://www.amazon.com/review/R11LIYW9RMDK9R            False      NaN
3     https://www.amazon.com/review/R3K9X391DJNTPZ            False      NaN
4      https://www.amazon.com/review/RP17IW9ZKENDZ            False      NaN
...                                            ...              ...      ...
6322   https://www.amazon.com/review/RABGOTWKLC1ZE             True      NaN
6323  https://www.amazon.com/review/R296C450ZKYYFX             True      NaN
6324  https://www.amazon.com/review/R3GH9SCGO3DZPU             True      NaN
6325  https://www.amazon.com/review/R3RUVOQYCGQB74             True      NaN
6326   https://www.amazon.com/review/R84TV4CYOWGTW             True      NaN

                                    cleaned_review_text  sentiment_score
0     coofandy men polo shirt fantastic blend style ...         0.292024
1     love look good fit well comfortable breathable...         0.560000
2     expectation low good could shirt sell one mist...         0.192321
3     pack multicolor shirt really brainer wear type...         0.307949
4     three polo shirt satisfied quality material go...         0.250000
...                                                 ...              ...
6322  super cute shrunk washed got couple wear lengt...         0.416667
6323  ive looking good boyfriend fit pair pant bit f...         0.229451
6324  look good give booty lift bought grey one came...         0.237500
6325  pant ran big could dont as like model picture ...         0.034615
6326  ordered daughter little long bad think would l...         0.096875

[6327 rows x 23 columns]>

__________________________________________________

               s.no  helpfulVoteCount       rating  reviewPosition  \
count   6327.000000       6327.000000  6320.000000     6327.000000
mean    5803.484748          3.336336     4.533228        5.374743
std     3833.648255         19.090762     0.855710        2.889921
min        0.000000          0.000000     1.000000        1.000000
25%     2103.500000          0.000000     4.000000        3.000000
50%     5969.000000          0.000000     5.000000        5.000000
75%     7572.500000          2.000000     5.000000        8.000000
max    14050.000000        710.000000     5.000000       10.000000

       sentiment_score
count      6327.000000
mean          0.307545
std           0.218020
min          -1.000000
25%           0.168568
50%           0.300000
75%           0.450000
max           1.000000

__________________________________________________

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6327 entries, 0 to 6326
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   s.no                 6327 non-null   int64
 1   helpfulVoteCount     6327 non-null   int64
 2   images/0             516 non-null    object
 3   images/1             212 non-null    object
 4   images/2             98 non-null     object
 5   images/3             49 non-null     object
 6   images/4             26 non-null     object
 7   images/5             14 non-null     object
 8   images/6             7 non-null      object
 9   images/7             5 non-null      object
 10  productASIN          6327 non-null   object
 11  productVariant       5836 non-null   object
 12  rating               6320 non-null   float64
 13  reviewID             6327 non-null   object
 14  reviewMetadata       6296 non-null   object
 15  reviewPosition       6327 non-null   int64
 16  reviewText           6289 non-null   object
 17  reviewTitle          6313 non-null   object
 18  reviewURL            6327 non-null   object
 19  verifiedPurchase     6327 non-null   bool
 20  videos/0             34 non-null     object
 21  cleaned_review_text  6288 non-null   object
 22  sentiment_score      6327 non-null   float64
dtypes: bool(1), float64(2), int64(3), object(17)
memory usage: 1.1+ MB
None

__________________________________________________

(6327, 23)

In [5]:
# Choose a data set

#  Checking for null values

print(df_prod.isna().sum(), "\n" + "_"*50 + "\n", df_rvew.isna().sum())
print("\n" + "_"*50 + "\n")
print(f"Product Shape | Review Shape")
print(df_prod.shape, " ---| ", df_rvew.shape)
print("\n" + "_"*50 + "\n")


# Choose the Domain Related Problem
# Choose a Relevant Indicator / KPI
# Use 3-attributes to form the KPI

# Apply ML

# Natural Land and processing techniques
# Prepare report

s.no                           0
about_item                     0
asin                           0
availability                  13
best_sellers_rank            170
brand_name                     0
brand_page_url                79
breadcrumbs                   13
customer_review_summary       94
default_variant/0             32
default_variant/1             70
default_variant/2            727
delivery_date                 26
fastest_delivery_date         61
list_price                   327
manufacturer                 462
model_number                 529
price_value                   21
product_description          457
product_url                    0
rating_count                   9
rating_distribution/1star      0
rating_distribution/2star      0
rating_distribution/3star      0
rating_distribution/4star      0
rating_distribution/5star      0
rating_stars                   9
recent_purchases             159
scrape_time                    0
seller_name                   21
seller_page_url              302
title                          0
all_images                     0
rank_1                       188
dtype: int64
__________________________________________________
 s.no                      0
helpfulVoteCount          0
images/0               5811
images/1               6115
images/2               6229
images/3               6278
images/4               6301
images/5               6313
images/6               6320
images/7               6322
productASIN               0
productVariant          491
rating                    7
reviewID                  0
reviewMetadata           31
reviewPosition            0
reviewText               38
reviewTitle              14
reviewURL                 0
verifiedPurchase          0
videos/0               6293
cleaned_review_text      39
sentiment_score           0
dtype: int64

__________________________________________________

Product Shape | Review Shape
(728, 34)  ---|  (6327, 23)

__________________________________________________

In [6]:
#  Creat dataset copies before permanently manipulating data
df_r = df_rvew.copy()
df_p = df_prod.copy()

#  To avoid Correlance Dropping columns with less than 90% NUll values

# Keep columns that have at least 80% non-null values



trsh1 = len(df_r) * 0.9
df_r_cln = df_r.dropna(axis=1, thresh=trsh1)
trsh2 = len(df_p) * 0.75
df_p_cln = df_p.dropna(axis=1, thresh=trsh2)

#  Checking for null values

print(df_p_cln.isna().sum(), "\n" + "_"*50 + "\n", df_r_cln.isna().sum())
print("\n" + "_"*50 + "\n")
print(f"Product Shape | Review Shape")
print(df_p_cln.shape, " ---| ", df_r_cln.shape)
print("\n" + "_"*50 + "\n")

s.no                           0
about_item                     0
asin                           0
availability                  13
best_sellers_rank            170
brand_name                     0
brand_page_url                79
breadcrumbs                   13
customer_review_summary       94
default_variant/0             32
default_variant/1             70
delivery_date                 26
fastest_delivery_date         61
price_value                   21
product_url                    0
rating_count                   9
rating_distribution/1star      0
rating_distribution/2star      0
rating_distribution/3star      0
rating_distribution/4star      0
rating_distribution/5star      0
rating_stars                   9
recent_purchases             159
scrape_time                    0
seller_name                   21
title                          0
all_images                     0
dtype: int64
__________________________________________________
 s.no                     0
helpfulVoteCount         0
productASIN              0
productVariant         491
rating                   7
reviewID                 0
reviewMetadata          31
reviewPosition           0
reviewText              38
reviewTitle             14
reviewURL                0
verifiedPurchase         0
cleaned_review_text     39
sentiment_score          0
dtype: int64

__________________________________________________

Product Shape | Review Shape
(728, 27)  ---|  (6327, 14)

__________________________________________________

In [7]:
df_p_cln.head()

,s.no,about_item,asin,availability,best_sellers_rank,brand_name,brand_page_url,breadcrumbs,customer_review_summary,default_variant/0,...,rating_distribution/2star,rating_distribution/3star,rating_distribution/4star,rating_distribution/5star,rating_stars,recent_purchases,scrape_time,seller_name,title,all_images
0,0,Premium Comfort: Crafted from a high-quality c...,B0B59BJG6Y,In Stock,"#56,836 in Clothing, Shoes & Jewelry (See Top ...",MLYENX Store,https://www.amazon.com/stores/MLYENX/page/1FCD...,"Clothing, Shoes & Jewelry › Men › Clothing › A...",Customers find the shirts comfortable and well...,size:Large,...,1%,7%,15%,75%,4.6 out of 5 stars,50+ bought,03-10-2025 21:42,Greenfive,4/5 Pack Mens Polo Shirts Short Sleeve Quick D...,['https://m.media-amazon.com/images/I/41yUF65P...
1,1,Material: Men's polo shirt is made of soft pol...,B0DLGB4RYH,In Stock,"#50,261 in Clothing, Shoes & Jewelry (See Top ...",COOFANDY Store,https://www.amazon.com/stores/COOFANDY/page/23...,"Clothing, Shoes & Jewelry › Men › Clothing › S...",NaN,size:X-Large,...,6%,11%,17%,66%,4.4 out of 5 stars,NaN,03-10-2025 21:42,COOFANDY,COOFANDY Men's Polo Shirts Short Sleeve Moistu...,['https://m.media-amazon.com/images/I/31a3mSs3...
2,2,"PERFORMANCE:These men polo shirts are soft,lig...",B0DRXF62JH,In Stock,"#69,641 in Clothing, Shoes & Jewelry (See Top ...",ZITY Store,https://www.amazon.com/stores/ZITY/page/F582B6...,"Clothing, Shoes & Jewelry › Men › Clothing › A...",NaN,size:X-Large,...,0%,0%,37%,63%,4.6 out of 5 stars,NaN,03-10-2025 21:42,ZITY®,ZITY 3 Pack Men Polo Shirts Short Sleeve with ...,['https://m.media-amazon.com/images/I/41J5q-Ua...
3,3,【Material】: These golf shirts for men are made...,B0DK5FZ325,In Stock,"#194,649 in Clothing, Shoes & Jewelry (See Top...",Rouen Store,https://www.amazon.com/stores/ROUEN/page/4C407...,"Clothing, Shoes & Jewelry › Men › Clothing › A...",NaN,size:Small,...,0%,0%,20%,80%,4.8 out of 5 stars,NaN,03-10-2025 21:43,MICHEL ROUEN,Rouen Mens Golf Shirt Moisture Wicking Dry Fit...,['https://m.media-amazon.com/images/I/31J1ttvf...
4,4,MOISTURE WICKING: The fabric of the summer gol...,B0BGXTC1FR,In Stock,"#3,664 in Clothing, Shoes & Jewelry (See Top 1...",V VALANCH Store,https://www.amazon.com/stores/VVALANCH/page/0E...,"Clothing, Shoes & Jewelry › Men › Clothing › A...",Customers find the shirt has a good fit and lo...,size:X-Large,...,2%,7%,17%,69%,4.4 out of 5 stars,NaN,03-10-2025 21:43,Zhengdaqian,V VALANCH Mens Polo Shirts Short Sleeve Moistu...,['https://m.media-amazon.com/images/I/31Ff+3Ib...

In [8]:
df_r_cln.head()

,s.no,helpfulVoteCount,productASIN,productVariant,rating,reviewID,reviewMetadata,reviewPosition,reviewText,reviewTitle,reviewURL,verifiedPurchase,cleaned_review_text,sentiment_score
0,0,0,B0DLGB4RYH,Color: BlackSize: X-Large,5.0,R2AUQFPJY5ERCZ,"Reviewed in the United States on March 6, 2025",1,‚úçÔ∏è The COOFANDY Men's Polo Shirt is a fant...,Stylish and Lightweight COOFANDY Polo Shirt,https://www.amazon.com/review/R2AUQFPJY5ERCZ,False,coofandy men polo shirt fantastic blend style ...,0.292024
1,1,0,B0DRXF62JH,Color: Bblack Grey NavySize: 3X-Large,5.0,R1YNLJ0QFLB1VT,"Reviewed in the United States on March 7, 2025",1,I love these. They look good. They fit well. T...,New favorite shirts,https://www.amazon.com/review/R1YNLJ0QFLB1VT,False,love look good fit well comfortable breathable...,0.560000
2,2,0,B0DRXF62JH,Color: Grey Navy DuckblueSize: Medium,4.0,R11LIYW9RMDK9R,"Reviewed in the United States on February 27, ...",2,My expectations were low -- how good could shi...,Incredibly Good Deal,https://www.amazon.com/review/R11LIYW9RMDK9R,False,expectation low good could shirt sell one mist...,0.192321
3,3,0,B0DRXF62JH,Color: Black Duckblue WineredSize: X-Large,5.0,R3K9X391DJNTPZ,"Reviewed in the United States on February 26, ...",3,This 3-pack of multi-color shirts is really a ...,Higher quality & breathable 3-pack shirt set t...,https://www.amazon.com/review/R3K9X391DJNTPZ,False,pack multicolor shirt really brainer wear type...,0.307949
4,4,0,B0DRXF62JH,Color: Bblack Grey NavySize: X-Large,5.0,RP17IW9ZKENDZ,"Reviewed in the United States on February 20, ...",4,With these three polo shirts I was very satisf...,Pocket Polos Looks Good,https://www.amazon.com/review/RP17IW9ZKENDZ,False,three polo shirt satisfied quality material go...,0.250000

In [9]:
# Since trust is an issue, in the line of work.
# Our main focus are with the ones whose verified Purchase = True, since their review will actually mean somthing
df_r_cln['verifiedPurchase'].value_counts()

# Passing its self to drop the non-purchasing reviews (all part of cleaning data)
df_r_cln = df_r_cln[df_r_cln['verifiedPurchase']]

In [10]:
import time
# There is a very huege possibilities that we could be dealing with  relational databases, so far similarity is pointing at 'ASIN'
# Finding Foreign key in the Database
# 1. Check if column is Unique

dup_cont = df_r_cln['productASIN'].duplicated().sum()
cont = len(df_r_cln['productASIN'])

print("Is the 'productASIN' column Unique: ")
time.sleep(3)
print(df_r_cln['productASIN'].is_unique)
time.sleep(3)
print("\n" + "_"*50 + "\n")
time.sleep(3)
# 2. Print UNique Value (Visualize what we dealing with)
# print(df_r_cln['productASIN'].unique())
print("What's the number of duplicated values:")
time.sleep(3)
print(f"{dup_cont} / {cont}")
time.sleep(3)
print("\n" + "_"*50 + "\n")
time.sleep(3)

# 3. Summarize: By determining the frequency of recurring duplicates
print(df_r_cln['productASIN'].value_counts())
print("\n" + "_"*50 + "\n")

Is the 'productASIN' column Unique:
False

__________________________________________________

What's the number of duplicated values:
5482 / 6167

__________________________________________________

productASIN
B074KL8RVS    19
B074KL2SHP    14
B07HR877BN    14
B08Q86H92W    13
B07DRMT92L    13
              ..
B0DS6141ZT     1
B01BDZMIK0     1
B0CSJ417P3     1
B0D1H1HV5F     1
B07FMX9FSF     1
Name: count, Length: 685, dtype: int64

__________________________________________________

In [11]:
print(df_p_cln['seller_name'].value_counts())
print("\n" + "_"*50 + "\n")

seller_name
Amazon.com               278
Dokotoo Flagship Shop     15
PAATM SHIVA               15
KISAHAPPARELS             10
ZITY®                      9
                        ...
GlobeCarry                 1
VooVeeYA                   1
ETTELO                     1
Lepunuo                    1
crazm                      1
Name: count, Length: 267, dtype: int64

__________________________________________________

In [12]:
print(df_p_cln['brand_name'].value_counts())
print("\n" + "_"*50 + "\n")

brand_name
Hanes Store                35
Amazon Essentials Store    24
Under Armour Store         23
Lee Store                  18
adidas Store               18
                           ..
Pudolla Store               1
FT FENTENG Store            1
Brand: KAOKLRNI             1
EKLENTSON Store             1
HILEELANG Store             1
Name: count, Length: 285, dtype: int64

__________________________________________________

In [13]:
print(df_p_cln['rating_stars'].value_counts())
print("\n" + "_"*50 + "\n")
len(df_p_cln['rating_stars'])
print("\n" + "_"*50 + "\n")
print(df_p_cln['recent_purchases'].value_counts())
print("\n" + "_"*50 + "\n")
len(df_p_cln['recent_purchases'])
print("\n" + "_"*50 + "\n")
print(df_r_cln['sentiment_score'].value_counts())
print("\n" + "_"*50 + "\n")
len(df_r_cln['sentiment_score'])

rating_stars
4.5 out of 5 stars    131
4.6 out of 5 stars    126
4.4 out of 5 stars    118
4.3 out of 5 stars     88
4.2 out of 5 stars     65
4.7 out of 5 stars     50
4.8 out of 5 stars     35
4.1 out of 5 stars     27
4 out of 5 stars       22
3.8 out of 5 stars     12
3.7 out of 5 stars      8
3.9 out of 5 stars      8
5 out of 5 stars        6
3.6 out of 5 stars      6
3.4 out of 5 stars      3
3.5 out of 5 stars      3
3 out of 5 stars        2
3.1 out of 5 stars      2
3.3 out of 5 stars      2
2.2 out of 5 stars      1
1 out of 5 stars        1
2.6 out of 5 stars      1
3.2 out of 5 stars      1
4.9 out of 5 stars      1
Name: count, dtype: int64

__________________________________________________


__________________________________________________

recent_purchases
100+ bought    108
200+ bought     76
1K+ bought      63
300+ bought     59
50+ bought      52
400+ bought     52
500+ bought     38
2K+ bought      26
700+ bought     22
600+ bought     21
800+ bought     14
3K+ bought      12
900+ bought     10
4K+ bought       7
5K+ bought       4
10K+ bought      2
9K+ bought       1
8K+ bought       1
7K+ bought       1
Name: count, dtype: int64

__________________________________________________


__________________________________________________

sentiment_score
 0.000000    244
 0.500000    161
 0.700000    122
 0.600000    111
 0.400000    102
            ...
-0.238889      1
 0.065758      1
 0.195750      1
 0.165306      1
 0.066804      1
Name: count, Length: 2949, dtype: int64

__________________________________________________

6167

In [14]:
print(df_p_cln['availability'].value_counts())
print("\n" + "_"*50 + "\n")

availability
In Stock                                       640
Currently unavailable.                          18
In stock                                        16
Only 1 left in stock - order soon.              14
Only 3 left in stock - order soon.              10
Only 5 left in stock - order soon.               6
Only 2 left in stock - order soon.               6
Available to ship in 1-2 days                    2
This item will be released on May 20, 2025.      1
Only 4 left in stock - order soon.               1
Temporarily out of stock.                        1
Name: count, dtype: int64

__________________________________________________

In [15]:
# Created New dataframe with the relation observed in 'asin' and 'productASIN'
# Merge the two DataFrames on their matching ID columns
df_ = pd.merge(df_p_cln, df_r_cln, left_on='asin', right_on='productASIN', how='inner')
# print(df_.head)
col = df_.columns[df_.notna().sum() > 0].tolist()
print(col)

['s.no_x', 'about_item', 'asin', 'availability', 'best_sellers_rank', 'brand_name', 'brand_page_url', 'breadcrumbs', 'customer_review_summary', 'default_variant/0', 'default_variant/1', 'delivery_date', 'fastest_delivery_date', 'price_value', 'product_url', 'rating_count', 'rating_distribution/1star', 'rating_distribution/2star', 'rating_distribution/3star', 'rating_distribution/4star', 'rating_distribution/5star', 'rating_stars', 'recent_purchases', 'scrape_time', 'seller_name', 'title', 'all_images', 's.no_y', 'helpfulVoteCount', 'productASIN', 'productVariant', 'rating', 'reviewID', 'reviewMetadata', 'reviewPosition', 'reviewText', 'reviewTitle', 'reviewURL', 'verifiedPurchase', 'cleaned_review_text', 'sentiment_score']

In [16]:
df0 = df_.copy()

In [18]:
df0 = df0.drop(columns=['s.no_x', 'asin', 'brand_page_url', 'product_url', 'rating_distribution/1star', 'rating_distribution/2star', 'rating_distribution/3star', 'rating_distribution/4star', 'rating_distribution/5star', 'title', 'all_images', 's.no_y', 'helpfulVoteCount', 'productASIN', 'default_variant/1','default_variant/0', 'reviewID', 'reviewMetadata', 'reviewPosition', 'reviewText', 'reviewTitle', 'reviewURL', 'cleaned_review_text'])

In [19]:
print(df0.info())
cols = df0.columns[df0.notna().sum() > 0].tolist()
print(cols)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6167 entries, 0 to 6166
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   about_item               6167 non-null   object
 1   availability             6070 non-null   object
 2   best_sellers_rank        4845 non-null   object
 3   brand_name               6167 non-null   object
 4   breadcrumbs              6101 non-null   object
 5   customer_review_summary  5794 non-null   object
 6   delivery_date            6023 non-null   object
 7   fastest_delivery_date    5798 non-null   object
 8   price_value              6062 non-null   float64
 9   rating_count             6167 non-null   object
 10  rating_stars             6167 non-null   object
 11  recent_purchases         5214 non-null   object
 12  scrape_time              6167 non-null   object
 13  seller_name              6062 non-null   object
 14  productVariant           5689 non-null   object
 15  rating                   6167 non-null   float64
 16  verifiedPurchase         6167 non-null   bool
 17  sentiment_score          6167 non-null   float64
dtypes: bool(1), float64(3), object(14)
memory usage: 825.2+ KB
None
['about_item', 'availability', 'best_sellers_rank', 'brand_name', 'breadcrumbs', 'customer_review_summary', 'delivery_date', 'fastest_delivery_date', 'price_value', 'rating_count', 'rating_stars', 'recent_purchases', 'scrape_time', 'seller_name', 'productVariant', 'rating', 'verifiedPurchase', 'sentiment_score']

In [20]:
print(df_p_cln['rating_count' ].value_counts())
print("\n" + "_"*50 + "\n")
len(df_p_cln['rating_count'])
print("\n" + "_"*50 + "\n")
print(df_p_cln['rating_stars'].value_counts())
print("\n" + "_"*50 + "\n")
len(df_p_cln['rating_stars'])
print("\n" + "_"*50 + "\n")
print(df_p_cln['about_item'].value_counts())
print("\n" + "_"*50 + "\n")
len(df_p_cln['about_item'])

rating_count
14 ratings        4
5 ratings         4
26 ratings        4
20 ratings        4
2 ratings         4
                 ..
2,108 ratings     1
14,823 ratings    1
10,572 ratings    1
8,110 ratings     1
19,982 ratings    1
Name: count, Length: 645, dtype: int64

__________________________________________________


__________________________________________________

rating_stars
4.5 out of 5 stars    131
4.6 out of 5 stars    126
4.4 out of 5 stars    118
4.3 out of 5 stars     88
4.2 out of 5 stars     65
4.7 out of 5 stars     50
4.8 out of 5 stars     35
4.1 out of 5 stars     27
4 out of 5 stars       22
3.8 out of 5 stars     12
3.7 out of 5 stars      8
3.9 out of 5 stars      8
5 out of 5 stars        6
3.6 out of 5 stars      6
3.4 out of 5 stars      3
3.5 out of 5 stars      3
3 out of 5 stars        2
3.1 out of 5 stars      2
3.3 out of 5 stars      2
2.2 out of 5 stars      1
1 out of 5 stars        1
2.6 out of 5 stars      1
3.2 out of 5 stars      1
4.9 out of 5 stars      1
Name: count, dtype: int64

__________________________________________________


__________________________________________________

about_item
Textured fabric that's soft, light & breathable|Material wicks sweat & dries really fast|Anti-odor technology prevents the growth of odor-causing microbes                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       3
Super-light HeatGear fabric delivers superior coverage without weighing you downMesh underarm & back panels for strategic ventilationMaterial wicks sweat & dries really fastErgonomic design keeps seams off high abrasion areas & increases durabilityHybrid raglan sleeve construction for added range of motion & comfortWrite-in locker tag on back of neck for your initials or number                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     3
PREMIUM QUALITY CRAFTMANSHIP: Our Sherwani sets are meticulously crafted with high quality materials and intricate detailing, a luxurious ethnic attire ensuring superior comfort and durability.MODERN & CONTEMPORARY DESIGN: While sherwani sets have traditional roots, modern designs have adapted the style to cater to contemporary tastes. Men can find sherwani sets with modern silhouettes, innovative cuts, and contemporary color combinations, blending aesthetics.HAND MADE IN INDIA: Individually made by skilled artisans, each sherwani set tunic is meticulously crafted and checked for finesse, ensuring exceptional quality.OCCASION AND GIFTING: OCCASION AND GIFTING: The Sherwani Set with high-quality fabric can be worn both casually and formally. It is suitable for occasions such as weddings, ceremonies, parties, regular wear, festivals, Lohri, Makar Sankranti, Baisakhi, Holi, Father's Day, Eid, Raksha Bandhan, Dussehra, Diwali, Navratri, Pooja, Christmas, Onam, Ganesha, business meetings, and daily use. Additionally, it can be given as a gift to family and friends.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             3
ELEGANT SHERWANI SET: Discover a wide range of elegantly designed Sherwanis that embody traditional charm and modern style, these sherwani sets are perfect for grooms and groomsmen, featuring exquisite and opulent designs.MODERN & CONTEMPORARY DESIGN: While sherwani sets have traditional roots, modern designs have adapted the style to cater to contemporary tastes. Men can find sherwani sets with modern silhouettes, innovative cuts, and contemporary color combinations, blending traditional aesthetics with a fresh and fashionable twist.OCCASION AND GIFTING: Sherwani Set with high-quality fabric can be worn both casually and formally. It is suitable for occasions such as weddings, ceremonies, parties, festivals, Lohri, Makar Sankranti, Baisakhi, Holi, Eid, Raksha Bandhan, Dussehra, Diwali, Navratri, Pooja, Onam, Ganesha, etc.HAND MADE IN INDIA: Individually made by skilled artisans, each sherwani set tunic is meticulously crafted and checked for finesse, ensuring exceptional quality.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              3
FLEECE TO FEEL GOOD ABOUT - This men's pullover sweatshirt is made with cotton sourced from American farms.STAYS SOFT - Thick, sturdy fleece keeps this crewneck sweatshirt warm and cozy.UNISEX SIZING - This sweatshirt is designed with a standard men’s fit that also creates an effortless, oversized look for women. Female model is 5'8" and wearing a size medium.MADE TO LAST - Double-needle stitching at the neck and armholes adds extra quality and sturdiness to this men's sweatshirt.CLASSIC SILHOUETTE - Basic crewneck sweatshirt shaping for that versatile look you love.BIG & TALL OPTIONS - This pullover sweatshirt is available in Big Men's sizing up to 3XL, so you can find your perfect fit.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ..
Comfortable High-Waist Fit: These cargo jean women feature a high-waisted design that flatters your figure and provides a comfortable, secure fit, perfect for all-day wear.Slight Stretch for Flexibility: With a touch of elasticity, these baggy jeans for women offer just the right amount of stretch, ensuring ease of movement without compromising style.Wide-Leg Silhouette: The wide-leg cut adds a modern and relaxed look to your outfit, making these jeans versatile enough for both casual and dressy occasions.Functional Cargo Pockets: Equipped with spacious cargo pockets, these wide leg cargo jean for women combine practicality with style, offering ample storage while enhancing the overall rugged aesthetic.Durable Denim Material: Made from premium denim with a hint of stretch, these pants are both durable and comfortable, providing a soft feel and a long-lasting addition to your wardrobe.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1
Buttery-Soft & Comfortable: Trendy jean look boot cut yoga dressy pants with 4 way-stretchy, quick-drying and sweat-wicking compressive fabric, designed with a high waistband. You can wear bootcut jeggings comfortably with tanks, T-shirts, or a sports bra for an easy athleisure look.Slightly Flared & Deep 4 Pockets: Casual flare leggings for women with 2 roomy front pockets & 2 back pockets for storing small personal items, such as your phone, cash, or keys. Just empty your hands and make your outing convenient with cute flared leggings.High Waist Tummy Control: Slimming fit bootcut dressy leggings for women are designed with high waistband and Buttery soft fabric without rolling down or slipping during workout like a gentle hug to your skin. Visually, bootcut leggings for women elongates the legs and accentuates curves.Customize Size Unique Design: Stretch lounge athletic pants with pockets can work with different inseam lengths, they're completely customizable which flatter every body type and shape. All you need to do is cut below the mark of bootleg yoga pants to trim off the extra length you don't need.EXCELLENT SERVICE: High waisted bootcut jeans leggings are stretchy, squat proof, comfortable flare pants, Just add these Bootcut Yoga Leggings for Women with Pockets to your cart by clicking the "Add-to-Cart" button.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   1
Jean For Women Excellent Workmanship, No Odor, Soft And Lightweight, Straight Design Stand Accentuate Your Attractive Legs, More Slender, Sexy, Is A Must-have In Your Closet.Trendy Jeans For Women 2025 Comes Light Blue Wash Process And Straight Design, 4 Pockets, Relaxed Fit Design More Comfortable To Wear, Casual.High Waisted Jeans For Women Is Perfect Choice For Your Daily Wear, Outdoor Activities, Office, Shopping, Club, Party, During The Holiday, Dates And Any Other OccasionsFlamingo Jeans For Women Which Can Be Worn In All Seasons, Is A Must-have Item For Your Mother, Wife And Friends To Wear With A Denim Jacket, Camisole And Loafers. They Will Be Very Happy And Love It.Stretchy Jeans For Women Recommened Hand/machine Wash In Cold Water, Do Not Bleach, Dry In A Dry Place. Please Allow 1/2 Inch Difference Due To Hand Measurement. Please Refer "size Chart" Before Ordering. If You Are Not Sure About The Size, Please Contact Us                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   1
Materials: Lepunuo Cargo Pants are made of high-quality cotton fabric and soft elastic wear-resistant fabric, suitable for all day wear. High Stretch, High Light, Moisture Wicking and Comfortable. Natural cotton fabrics are not recommended for tumble drying or low temperature drying.Features: Cargo pants with 6 pockets, stretch elastic high waist, relaxed fit, zipper and button closure, hip hop joggers sweatpants, wide leg cargo pants, Y2K style, hippie outfits, and the loose fit is ideal for casual or sporty.Match: This cargo pants with smooth contour and beautiful appearance, basic style which is bloggers favorite, perfect for your everyday essentials collection in your closet. These cool girl style pants can be paired with Crop Tops, T-shirts, sweaters, cardigans and jackets for spring, summer, fall and winter.Occasion: This cargo pant is simple but stylish, it is a all-match item that every fashionable woman or girls will choose anywhere, such as school, dance room, vacation, party, dating, picnics, home, street, gym, running, club, daily life, work, shopping, office, indoor and outdoor activities.Size & Garment Care: Please refer to the size chart in the instructions to select your normal size(Loose fit design, normal size can be worn in a baggy style, or we recommend sizing down for a better fit). Fully machine washable for easy care. Wash before wearing, wash with like colors. Wash cold water; Do not bleach; Do not wring or twist; Line dry in the shade.                                                                                                                                                                                                                                                                                                                                                                     1

728

In [80]:
# Encoding Data

# Remove string formatting, strip commas, and cast to integer
# df0['ratings_counts'] = df0['rating_count'].str.replace(' ratings', '', case=False)
# df0['ratings_counts'] = df0['rating_count'].str.replace(' rating', '', case=False)

# df0['ratings_counts'] = df0['rating_count'].str.replace(' rating', '', case=False)
# df0['ratings_counts'] = df0['rating_count'].str.replace('s', '', case=False)

# df0['ratings_count'] = df0['ratings_counts'].str.replace(',', '').astype(int)

df0['ratings_column'] = (df0['rating_count']
                         .str.replace(' ratings', '')
                         .str.replace(' rating', '')
                         .str.replace(',', '')
                         .astype(int))

print(df0['ratings_column' ].value_counts())
print("\n" + "_"*50 + "\n")
len(df0['ratings_column'])
print("\n" + "_"*50 + "\n")

df0['rate_star'] = (df0['rating_stars'].str.replace(' out of 5 stars', '').astype(float))
print(df0['rate_star' ].value_counts())
print("\n" + "_"*50 + "\n")
len(df0['rate_star'])
print("\n" + "_"*50 + "\n")

# Define the custom tier thresholds and integer labels
bins = [1.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]
labels = [1, 2, 3, 4, 5, 6]

# Apply the encoding (include_lowest ensures 1.0 is captured)
df0['rating_encoded'] = pd.cut(df0['rate_star'], bins=bins, labels=labels, include_lowest=True)
print(df0['rating_encoded'].value_counts())
df0.info()

ratings_column
95       21
624      20
763      20
812      20
85       20
         ..
19323     1
504       1
12963     1
13517     1
1475      1
Name: count, Length: 642, dtype: int64

__________________________________________________


__________________________________________________

rate_star
4.5    1179
4.6    1125
4.4    1035
4.3     809
4.2     587
4.7     416
4.8     285
4.1     240
4.0     155
3.8      94
3.9      66
3.6      49
3.7      49
3.4      13
3.3      12
3.2      10
4.9      10
3.0       9
3.1       9
3.5       7
5.0       4
2.2       2
1.0       1
2.6       1
Name: count, dtype: int64

__________________________________________________


__________________________________________________

rating_encoded
5    3850
6    1840
4     413
3      51
2      10
1       3
Name: count, dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6167 entries, 0 to 6166
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   about_item               6167 non-null   object
 1   availability             6070 non-null   object
 2   best_sellers_rank        4845 non-null   object
 3   brand_name               6167 non-null   object
 4   breadcrumbs              6101 non-null   object
 5   customer_review_summary  5794 non-null   object
 6   delivery_date            6023 non-null   object
 7   fastest_delivery_date    5798 non-null   object
 8   price_value              6062 non-null   float64
 9   rating_count             6167 non-null   object
 10  rating_stars             6167 non-null   object
 11  recent_purchases         5214 non-null   object
 12  scrape_time              6167 non-null   object
 13  seller_name              6062 non-null   object
 14  productVariant           5689 non-null   object
 15  rating                   6167 non-null   float64
 16  verifiedPurchase         6167 non-null   bool
 17  sentiment_score          6167 non-null   float64
 18  ratings_column           6167 non-null   int64
 19  rate_star                6167 non-null   float64
 20  rating_encoded           6167 non-null   category
dtypes: bool(1), category(1), float64(4), int64(1), object(14)
memory usage: 927.8+ KB

In [67]:
import re

df02= df_prod.copy()
date_col = df02[['delivery_date','fastest_delivery_date']]

In [69]:
print(df02['fastest_delivery_date'].value_counts())
print("\n" + "_"*50 + "\n")
print(df02['delivery_date'].value_counts())

fastest_delivery_date
Tomorrow, March 11     491
Wednesday, March 12     83
Today                   49
Tomorrow                 7
Thursday, March 13       5
March 14 - 19            2
Friday, March 14         2
March 13 - 18            2
March 17 - 19            2
Sunday, March 16         1
March 12 - 14            1
March 23 - April 6       1
March 20 - 22            1
March 19 - 25            1
March 22 - 27            1
March 23 - 30            1
March 19 - 23            1
March 22 - April 6       1
March 19 - 22            1
March 22 - 26            1
March 12 - 13            1
March 16 - 17            1
Saturday, March 15       1
March 18 - 19            1
Monday, March 17         1
March 17 - 20            1
March 14 - 17            1
March 21 - 31            1
March 21 - 22            1
March 23 - April 2       1
Thursday, March 20       1
March 14 - 18            1
March 18 - 21            1
Name: count, dtype: int64

__________________________________________________

delivery_date
Saturday, March 15     610
March 31 - April 9      12
Monday, March 17         5
Wednesday, March 12      4
April 1 - 10             4
Thursday, March 13       4
March 20 - 21            4
March 20 - 26            3
March 14 - 18            3
March 14 - 19            3
March 19 - 26            2
April 9 - 22             2
March 17 - 21            2
April 8 - 18             2
April 8 - 21             2
Tuesday, March 18        2
Friday, March 14         2
March 15 - 19            2
March 13 - 17            2
March 13 - 14            1
March 23 - April 1       1
March 18 - 21            1
March 21 - 24            1
March 17 - 22            1
March 22 - 30            1
March 18 - 24            1
March 19 - 28            1
March 22 - April 9       1
March 17 - 20            1
March 22 - 28            1
March 17 - 18            1
March 15 - 18            1
March 16 - 19            1
March 12 - 13            1
March 23 - April 9       1
April 2 - 11             1
March 18 - 23            1
March 21 - 31            1
April 1 - 11             1
March 17 - 19            1
March 16 - 18            1
March 21 - 25            1
March 21 - April 2       1
March 23 - April 3       1
March 20 - 23            1
March 17 - 25            1
March 18 - 25            1
March 28 - April 7       1
March 17 - 24            1
March 26 - April 1       1
March 14 - 17            1
Name: count, dtype: int64

In [79]:
# Cleaning and formating the irregular inconsistent date-time data, for easy computation

from datetime import datetime, timedelta

# 1. Define timeline context (March 15, 2025 is Saturday -> Today is March 10, 2025)
base_today = datetime(2025, 3, 10)
base_tomorrow = base_today + timedelta(days=1)

def parse_kpi_dates(val):
    if pd.isna(val):
        return pd.Series([pd.NaT, pd.NaT])
    
    text = str(val).strip()
    
    # Context 1: Absolute single relative terms
    if text.lower() == 'today':
        return pd.Series([base_today, base_today])
    if text.lower() == 'tomorrow':
        return pd.Series([base_tomorrow, base_tomorrow])
        
    # Context 2: Relative terms with dates (e.g., "Tomorrow, March 11")
    # Strip weekdays ("Wednesday, ") or relative words ("Tomorrow, ")
    text_cleaned = re.sub(r'^(Tomorrow|Today|Yesterday|[A-Za-z]+),\s*', '', text, flags=re.IGNORECASE)
    
    # Month map to convert names to digits for range processing
    months_map = {
        'jan': 1, 'feb': 2, 'mar': 3, 'apr': 4, 'may': 5, 'jun': 6,
        'jul': 7, 'aug': 8, 'sep': 9, 'oct': 10, 'nov': 11, 'dec': 12
    }
    
    # Context 3: Date Ranges (e.g., "March 14 - 19" or "March 23 - April 6")
    if '-' in text_cleaned:
        try:
            # Split into start and end string blocks
            parts = [p.strip() for p in text_cleaned.split('-')]
            
            # Find the months referenced in the string fragments
            start_month_match = re.search(r'[A-Za-z]+', parts[0])
            end_month_match = re.search(r'[A-Za-z]+', parts[1])
            
            start_month_str = start_month_match.group(0)[:3].lower()
            start_month = months_map[start_month_str]
            start_day = int(re.search(r'\d+', parts[0]).group(0))
            
            # If the end part doesn't have a month explicitly, it shares the start month
            if end_month_match:
                end_month_str = end_month_match.group(0)[:3].lower()
                end_month = months_map[end_month_str]
            else:
                end_month = start_month
            end_day = int(re.search(r'\d+', parts[1]).group(0))
            
            start_dt = datetime(2025, start_month, start_day)
            end_dt = datetime(2025, end_month, end_day)
            return pd.Series([start_dt, end_dt])
        except Exception:
            return pd.Series([pd.NaT, pd.NaT])
            
    # Context 4: Standard Single Dates (e.g., "March 11")
    try:
        parsed_date = datetime.strptime(text_cleaned, "%B %d").replace(year=2025)
        return pd.Series([parsed_date, parsed_date])
    except Exception:
        return pd.Series([pd.NaT, pd.NaT])

# 2. Apply across the entire dataset expanding into two clean columns
df02[['fastest_delivery_date_strt', 'fastest_delivery_date__end']] = df02['fastest_delivery_date'].apply(parse_kpi_dates)

df02[['delivery_date_strt', 'delivery_date_end']] = df02['delivery_date'].apply(parse_kpi_dates)

In [78]:
# cross check before data manipulation begins

# 1. Clean the text column by removing hidden spaces on the fly
clean_series = df02['fastest_delivery_date'].astype(str).str.strip()

# 2. Filter using clean string values
condition = clean_series.isin(['Today', 'Tomorrow'])
target_columns = ['fastest_delivery_date', 'fastest_delivery_date_strt', 'scrape_time','fastest_delivery_date__end']

# 3. Filter and print the resulting rows
print(df02.loc[condition, target_columns])
target_columns2 = ['delivery_date', 'delivery_date_strt', 'scrape_time','delivery_date_end']
print(df02[target_columns2])

    fastest_delivery_date fastest_delivery_date_strt       scrape_time  \
5                  Today                  2025-03-10  03-10-2025 21:43
6                  Today                  2025-03-10  03-10-2025 21:43
25                 Today                  2025-03-10  03-10-2025 21:44
59                 Today                  2025-03-10  03-10-2025 21:46
60                 Today                  2025-03-10  03-10-2025 21:46
61                 Today                  2025-03-10  03-10-2025 21:46
62                 Today                  2025-03-10  03-10-2025 21:46
69                 Today                  2025-03-10  03-10-2025 21:47
72                 Today                  2025-03-10  03-10-2025 21:47
73                 Today                  2025-03-10  03-10-2025 21:47
74                 Today                  2025-03-10  03-10-2025 21:47
78                 Today                  2025-03-10  03-10-2025 21:47
87                 Today                  2025-03-10  03-10-2025 21:48
89                 Today                  2025-03-10  03-10-2025 21:48
92                 Today                  2025-03-10  03-10-2025 21:48
95                 Today                  2025-03-10  03-10-2025 21:48
101                Today                  2025-03-10  03-10-2025 21:49
103                Today                  2025-03-10  03-10-2025 21:49
104                Today                  2025-03-10  03-10-2025 21:49
199                Today                  2025-03-10  03-10-2025 21:55
201                Today                  2025-03-10  03-10-2025 21:55
202                Today                  2025-03-10  03-10-2025 21:55
207                Today                  2025-03-10  03-10-2025 21:55
208                Today                  2025-03-10  03-10-2025 21:55
214                Today                  2025-03-10  03-10-2025 21:56
215                Today                  2025-03-10  03-10-2025 21:56
226                Today                  2025-03-10  03-10-2025 21:56
227                Today                  2025-03-10  03-10-2025 21:56
297                Today                  2025-03-10  03-10-2025 22:01
299                Today                  2025-03-10  03-10-2025 22:01
302                Today                  2025-03-10  03-10-2025 22:01
309                Today                  2025-03-10  03-10-2025 22:02
311                Today                  2025-03-10  03-10-2025 22:02
314                Today                  2025-03-10  03-10-2025 22:02
318                Today                  2025-03-10  03-10-2025 22:02
323                Today                  2025-03-10  03-10-2025 22:03
340                Today                  2025-03-10  03-10-2025 22:04
341                Today                  2025-03-10  03-10-2025 22:04
344                Today                  2025-03-10  03-10-2025 22:04
345                Today                  2025-03-10  03-10-2025 22:04
346                Today                  2025-03-10  03-10-2025 22:04
348                Today                  2025-03-10  03-10-2025 22:04
350                Today                  2025-03-10  03-10-2025 22:04
351                Today                  2025-03-10  03-10-2025 22:04
353                Today                  2025-03-10  03-10-2025 22:05
361                Today                  2025-03-10  03-10-2025 22:05
380                Today                  2025-03-10  03-10-2025 22:06
384                Today                  2025-03-10  03-10-2025 22:06
538                Today                  2025-03-10  03-10-2025 22:41
576             Tomorrow                  2025-03-11  03-10-2025 23:45
643             Tomorrow                  2025-03-11  03-11-2025 00:37
645             Tomorrow                  2025-03-11  03-11-2025 00:38
646             Tomorrow                  2025-03-11  03-11-2025 00:39
665             Tomorrow                  2025-03-11  03-11-2025 00:47
666             Tomorrow                  2025-03-11  03-11-2025 00:47
667             Tomorrow                  2025-03-11  03-11-2025 00:47

    fastest_delivery_date__end
5                   2025-03-10
6                   2025-03-10
25                  2025-03-10
59                  2025-03-10
60                  2025-03-10
61                  2025-03-10
62                  2025-03-10
69                  2025-03-10
72                  2025-03-10
73                  2025-03-10
74                  2025-03-10
78                  2025-03-10
87                  2025-03-10
89                  2025-03-10
92                  2025-03-10
95                  2025-03-10
101                 2025-03-10
103                 2025-03-10
104                 2025-03-10
199                 2025-03-10
201                 2025-03-10
202                 2025-03-10
207                 2025-03-10
208                 2025-03-10
214                 2025-03-10
215                 2025-03-10
226                 2025-03-10
227                 2025-03-10
297                 2025-03-10
299                 2025-03-10
302                 2025-03-10
309                 2025-03-10
311                 2025-03-10
314                 2025-03-10
318                 2025-03-10
323                 2025-03-10
340                 2025-03-10
341                 2025-03-10
344                 2025-03-10
345                 2025-03-10
346                 2025-03-10
348                 2025-03-10
350                 2025-03-10
351                 2025-03-10
353                 2025-03-10
361                 2025-03-10
380                 2025-03-10
384                 2025-03-10
538                 2025-03-10
576                 2025-03-11
643                 2025-03-11
645                 2025-03-11
646                 2025-03-11
665                 2025-03-11
666                 2025-03-11
667                 2025-03-11
          delivery_date delivery_date_strt       scrape_time delivery_date_end
0    Saturday, March 15         2025-03-15  03-10-2025 21:42        2025-03-15
1    Saturday, March 15         2025-03-15  03-10-2025 21:42        2025-03-15
2    Saturday, March 15         2025-03-15  03-10-2025 21:42        2025-03-15
3    Saturday, March 15         2025-03-15  03-10-2025 21:43        2025-03-15
4    Saturday, March 15         2025-03-15  03-10-2025 21:43        2025-03-15
..                  ...                ...               ...               ...
723  Saturday, March 15         2025-03-15  03-11-2025 02:15        2025-03-15
724  Saturday, March 15         2025-03-15  03-11-2025 02:15        2025-03-15
725  Saturday, March 15         2025-03-15  03-11-2025 02:15        2025-03-15
726  Saturday, March 15         2025-03-15  03-11-2025 02:15        2025-03-15
727  Saturday, March 15         2025-03-15  03-11-2025 02:15        2025-03-15

[728 rows x 4 columns]

In [81]:
# Data Preparation and Modeling

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

df02.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 728 entries, 0 to 727
Data columns (total 38 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   s.no                        728 non-null    int64
 1   about_item                  728 non-null    object
 2   asin                        728 non-null    object
 3   availability                715 non-null    object
 4   best_sellers_rank           558 non-null    object
 5   brand_name                  728 non-null    object
 6   brand_page_url              649 non-null    object
 7   breadcrumbs                 715 non-null    object
 8   customer_review_summary     634 non-null    object
 9   default_variant/0           696 non-null    object
 10  default_variant/1           658 non-null    object
 11  default_variant/2           1 non-null      object
 12  delivery_date               702 non-null    object
 13  fastest_delivery_date       667 non-null    object
 14  list_price                  401 non-null    object
 15  manufacturer                266 non-null    object
 16  model_number                199 non-null    object
 17  price_value                 707 non-null    float64
 18  product_description         271 non-null    object
 19  product_url                 728 non-null    object
 20  rating_count                719 non-null    object
 21  rating_distribution/1star   728 non-null    object
 22  rating_distribution/2star   728 non-null    object
 23  rating_distribution/3star   728 non-null    object
 24  rating_distribution/4star   728 non-null    object
 25  rating_distribution/5star   728 non-null    object
 26  rating_stars                719 non-null    object
 27  recent_purchases            569 non-null    object
 28  scrape_time                 728 non-null    object
 29  seller_name                 707 non-null    object
 30  seller_page_url             426 non-null    object
 31  title                       728 non-null    object
 32  all_images                  728 non-null    object
 33  rank_1                      540 non-null    float64
 34  fastest_delivery_date_strt  667 non-null    datetime64[ns]
 35  fastest_delivery_date__end  667 non-null    datetime64[ns]
 36  delivery_date_strt          702 non-null    datetime64[ns]
 37  delivery_date_end           702 non-null    datetime64[ns]
dtypes: datetime64[ns](4), float64(2), int64(1), object(31)
memory usage: 216.2+ KB

In [82]:
# Show Statistical summary for both numerical and categoricla columns
df02.describe( include='all' )

,s.no,about_item,asin,availability,best_sellers_rank,brand_name,brand_page_url,breadcrumbs,customer_review_summary,default_variant/0,...,scrape_time,seller_name,seller_page_url,title,all_images,rank_1,fastest_delivery_date_strt,fastest_delivery_date__end,delivery_date_strt,delivery_date_end
count,728.000000,728,728,715,558,728,649,715,634,696,...,728,707,426,728,728,540.000000,667,667,702,702
unique,NaN,697,728,11,539,285,237,140,616,118,...,120,267,426,704,714,NaN,NaN,NaN,NaN,NaN
top,NaN,"Textured fabric that's soft, light & breathabl...",B0C2VD1HN2,In Stock,"#67 in Clothing, Shoes & Jewelry (See Top 100 ...",Hanes Store,https://www.amazon.com/stores/Hanes/page/F8302...,"Clothing, Shoes & Jewelry › Men › Clothing › J...",Customers find the shirt has a good fit and st...,size:Large,...,03-10-2025 22:38,Amazon.com,https://www.amazon.com/gp/help/seller/at-a-gla...,Under Armour Men's Tech Golf Polo,['https://m.media-amazon.com/images/I/412gm7Sm...,NaN,NaN,NaN,NaN,NaN
freq,NaN,3,1,640,3,35,35,52,3,168,...,18,278,1,3,2,NaN,NaN,NaN,NaN,NaN
mean,423.361264,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,174.622222,2025-03-11 09:01:53.343328512,2025-03-11 13:27:26.176911616,2025-03-15 20:18:27.692307968,2025-03-16 13:40:30.769230848
min,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.000000,2025-03-10 00:00:00,2025-03-10 00:00:00,2025-03-12 00:00:00,2025-03-12 00:00:00
25%,184.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,18.000000,2025-03-11 00:00:00,2025-03-11 00:00:00,2025-03-15 00:00:00,2025-03-15 00:00:00
50%,371.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,56.500000,2025-03-11 00:00:00,2025-03-11 00:00:00,2025-03-15 00:00:00,2025-03-15 00:00:00
75%,553.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,220.250000,2025-03-11 00:00:00,2025-03-11 00:00:00,2025-03-15 00:00:00,2025-03-15 00:00:00
max,1011.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,994.000000,2025-03-23 00:00:00,2025-04-06 00:00:00,2025-04-09 00:00:00,2025-04-22 00:00:00
std,293.923401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,240.115097,NaN,NaN,NaN,NaN

In [85]:
# 1. Force both columns to datetime, turning unparseable or empty values into NaT (Not a Time)
start_dt = pd.to_datetime(df02['delivery_date_strt'], errors='coerce')
scrape_dt = pd.to_datetime(df02['scrape_time'], errors='coerce')

# 2. Subtract the dates directly, then extract the days as integers using .dt.days
# (This avoids using .dt.date which can sometimes revert the series to an 'object' type)
df02['delivery_period_int'] = (start_dt - scrape_dt).dt.days

# 3. Optional: Fill any missing/error rows with 0 (or leave as NaN if preferred)
df02['delivery_period_int'] = df02['delivery_period_int'].fillna(0).astype(int)

In [86]:
# Show Statistical summary for both numerical and categoricla columns
df02.describe( include='all' )

,s.no,about_item,asin,availability,best_sellers_rank,brand_name,brand_page_url,breadcrumbs,customer_review_summary,default_variant/0,...,seller_name,seller_page_url,title,all_images,rank_1,fastest_delivery_date_strt,fastest_delivery_date__end,delivery_date_strt,delivery_date_end,delivery_period_int
count,728.000000,728,728,715,558,728,649,715,634,696,...,707,426,728,728,540.000000,667,667,702,702,728.000000
unique,NaN,697,728,11,539,285,237,140,616,118,...,267,426,704,714,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,"Textured fabric that's soft, light & breathabl...",B0C2VD1HN2,In Stock,"#67 in Clothing, Shoes & Jewelry (See Top 100 ...",Hanes Store,https://www.amazon.com/stores/Hanes/page/F8302...,"Clothing, Shoes & Jewelry › Men › Clothing › J...",Customers find the shirt has a good fit and st...,size:Large,...,Amazon.com,https://www.amazon.com/gp/help/seller/at-a-gla...,Under Armour Men's Tech Golf Polo,['https://m.media-amazon.com/images/I/412gm7Sm...,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,3,1,640,3,35,35,52,3,168,...,278,1,3,2,NaN,NaN,NaN,NaN,NaN,NaN
mean,423.361264,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,174.622222,2025-03-11 09:01:53.343328512,2025-03-11 13:27:26.176911616,2025-03-15 20:18:27.692307968,2025-03-16 13:40:30.769230848,4.527473
min,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.000000,2025-03-10 00:00:00,2025-03-10 00:00:00,2025-03-12 00:00:00,2025-03-12 00:00:00,0.000000
25%,184.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,18.000000,2025-03-11 00:00:00,2025-03-11 00:00:00,2025-03-15 00:00:00,2025-03-15 00:00:00,4.000000
50%,371.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,56.500000,2025-03-11 00:00:00,2025-03-11 00:00:00,2025-03-15 00:00:00,2025-03-15 00:00:00,4.000000
75%,553.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,220.250000,2025-03-11 00:00:00,2025-03-11 00:00:00,2025-03-15 00:00:00,2025-03-15 00:00:00,4.000000
max,1011.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,994.000000,2025-03-23 00:00:00,2025-04-06 00:00:00,2025-04-09 00:00:00,2025-04-22 00:00:00,29.000000
std,293.923401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,240.115097,NaN,NaN,NaN,NaN,3.624282